CREATE TYPE NUCLSEQ;

CREATE FUNCTION nuclseq_in(CSTRING)
    RETURNS NUCLSEQ
    AS 'MODULE_PATHNAME'
    LANGUAGE C IMMUTABLE STRICT;

CREATE FUNCTION nuclseq_out(NUCLSEQ)
    RETURNS CSTRING
    AS 'MODULE_PATHNAME'
    LANGUAGE C IMMUTABLE STRICT;

CREATE TYPE nuclseq (
    internallength = VARIABLE,
    input = nuclseq_in,
    output = nuclseq_out
);

CREATE FUNCTION nuclseq_len(NUCLSEQ)
    RETURNS INTEGER
    AS 'MODULE_PATHNAME'
    LANGUAGE C IMMUTABLE STRICT;

CREATE FUNCTION nuclseq_content(NUCLSEQ, CSTRING)
    RETURNS DOUBLE PRECISION
    AS 'MODULE_PATHNAME'
    LANGUAGE C IMMUTABLE STRICT;

CREATE FUNCTION nuclseq_complement(NUCLSEQ)
    RETURNS NUCLSEQ
    AS 'MODULE_PATHNAME'
    LANGUAGE C IMMUTABLE STRICT;

CREATE FUNCTION yoyo_v1(INTEGER)
    RETURNS SETOF INTEGER
    AS 'MODULE_PATHNAME'
    LANGUAGE C VOLATILE STRICT;

CREATE TYPE bwa_result AS (
    alpha INTEGER,
    beta INTEGER,
    gamma NUCLSEQ
);

CREATE FUNCTION yoyo_v2()
    RETURNS SETOF bwa_result
    AS 'MODULE_PATHNAME'
    LANGUAGE C IMMUTABLE STRICT;
